controller_list:
  - name: fake_gripper_controller
    joints:
      - p4_hand_roll
      - p4_hand_pitch
      - p4_instrument_slide
      - p4_instrument_roll
      - p4_instrument_pitch
      - p4_instrument_jaw_right